### ISSUE TITLE
Implement Custom RNG rather than patching randombytes_sysrandom.c

### ISSUE THREAD

**Issue by charlesportwoodii** [charlesportwoodii/libsodium-uwp#1]
`libsodium` allows for different RNG sources to be used rather than the default ones. Details on how to perform this are available at https://download.libsodium.org/doc/advanced/custom_rng.html.

Implementing the RNG source is pretty trivial, however getting it to properly look and load into the runtime component _before_ `sodium_init`/library initialization is problematic, as `wincrypt.h` is not available.

This may involve removing implementing a library level `randombytes.c` that loads our `randombytes_uwp.c` rather than `libsodiums` `RANDOMBYTES_DEFAULT_IMPLEMENTATION`.

**Comment by jedisct1** [comment]
May https://github.com/jedisct1/libsodium/commit/49741c59e89f7cb83a7379353cf68f8ad6731140 help?

**Comment by charlesportwoodii** [comment]
@jedisct1: It might! Let me play around with it.

Honestly the trickiest part is finding the right spot to place that into so that the compiler picks it up _without_ having to modify the libsodium source code to do so. It's pretty trivial to add it to `randombytes.c`, of course defining this _outside_ of the libsodium source then getting libsodium to pick it up is the tricky part.

Thanks!

**Comment by charlesportwoodii** [comment]
@jedisct1 That most certainly resolves this issue. My previous comment can be ignored - I was clearly was a bit tired yesterday evening.

Thanks!
