### ISSUE TITLE
Question: Can I use this from a C++ UWP?

### ISSUE THREAD

**Issue by bwjohns4** [charlesportwoodii/libsodium-uwp#26]
I am writing a native module for a React Native Windows application which uses a C++ UWP app. Will this library work for that?

**Comment by charlesportwoodii** [comment]
I candidly don't know. If you can, I imagine you'd have to compile this down to a C# Windows Runtime Component. I don't really know what's involved in that. 

If you're using C++ though, it would probably be easier to just to include the libsodium c lib directly instead.

**Comment by charlesportwoodii** [comment]
autoclose
