### ISSUE TITLE
Curve25519 scalar mult conversation

### ISSUE THREAD

**Issue by BoBiene** [charlesportwoodii/libsodium-uwp#4]
Hi,

thank you for the port to UWP. 

Is it possible to make 

`crypto_scalarmult_curve25519(s,sk,pk)`

Available too?

**Comment by charlesportwoodii** [comment]
`crypto_scalarmult_curve25519(q, n, p)` is delegated to `crypto_scalarmult` in https://github.com/jedisct1/libsodium/blob/68564326e1e9dc57ef03746f85734232d20ca6fb/src/libsodium/crypto_scalarmult/crypto_scalarmult.c#L17.

libsodum-uwp implements this as `Sodium.ScalarMult.Mult(byte[] sk, byte[] pk)` (https://github.com/charlesportwoodii/libsodium-uwp/blob/master/libsodium-uwp/Sodium.cpp#L671). Some of the ScalarMult stuff just isn't documented yet.

Does that cover what you need?

**Comment by BoBiene** [comment]
Yea looks like
Realy fast answer, thank you 👍
