### ISSUE TITLE
hsalsa20 implementation

### ISSUE THREAD

**Issue by BoBiene** [charlesportwoodii/libsodium-uwp#5]
Can you please implement support for

`crypto_core_hsalsa20(k,_0,s,sigma)`

**Comment by charlesportwoodii** [comment]
`crypto_core_hsalsa20` is implemented by `crypto_secretbox_open_detached`. This'll be implemented once I get around to implemented detached boxed (specifically detached secret box).

Would that cover what you need?

**Comment by BoBiene** [comment]
I plan to develop a application implementing the API descriped here:
https://nuki.io/wp-content/uploads/2016/04/20160731-Smartlock-API-v1.02.pdf

Needed NaCl functions are explained on page 7.

Is it difficult to make them available for UWP?

**Comment by charlesportwoodii** [comment]
Not necessarily - the `crypto_core_*` functions just less documented than the others. I wasn't _really_ looking to implement anything outside of the functionality defined in libsodium-net (this is more of a port of that than all of libsodium itself). I have no problem implementing it - I'd need to find some documentation/a reference implementation to compare against.

Lemme search around for a reference implementation and get back to you.

**Comment by BoBiene** [comment]
You are awsome!

On page 30 in the linked PDF you can find test cases if they help.
Many thanks in advance!

**Comment by charlesportwoodii** [comment]
8078a71 should resolve this. Reference implementation/test was performed against section 8 of "Cryptography in NaCL" (https://cr.yp.to/highspeed/naclcrypto-20090310.pdf).

Lemme know if that does it for you.

**Comment by BoBiene** [comment]
Looks good. I can see the signature. I have tried to reproduce the sample in the linked PDF from the Smart-Lock. But I got stucked at the point calling the Sodium.KDF.HSalsa20 because i don't no wich parameters i have to pass.

I have made a request to the vendor. Hopfully they get back to morrow.

**Comment by charlesportwoodii** [comment]
The parameter order is the same, sans `k` which is returned rather than accepted as an input parameter. 

`crypto_core_hsalsa20(k,_0,s,sigma)` => `byte[] k = Sodium.KDF.HSalsa20(_0, s, sigma)`

At a cursory glance of their API docs, this should do what you need:

``` C#
var _0 = new byte[16];
var sigma = System.Text.Encoding.UTF8.GetBytes("expand 32­-byte k");
var s = Sodium.ScalarMult.Mult(secretKey, publicKey);

var kdf1 = Sodium.KDF.HSalsa20(_0, s, sigma);
```

**Comment by BoBiene** [comment]
Jep, thank you it is working now. 
After i found out that a copy and paste of the "expand 32-byte k" string out of the PDF will add a unvisible second "-" sign. So the sigma array was 17-Bytes long not 16-Bytes...

String in Notepad++
![image](https://cloud.githubusercontent.com/assets/23037659/19713445/852df0a6-9b46-11e6-9ecf-834b9f84ee48.png)

Sadly the Visual Studio is not showing this string.

Thanks again for you great help!

**Comment by charlesportwoodii** [comment]
Got it. Glad you got it worked out!
