### ISSUE TITLE
Compiling with ARM or x64 as target

### ISSUE THREAD

**Issue by BoBiene** [charlesportwoodii/libsodium-uwp#6]
If i change my target platform to ARM or x64 i get this error while compiling my project:

`1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: Die Ladung enthält mehrere Dateien mit dem gleichen Zielpfad "Sodium.winmd". Quelldateien: 
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: C:\Users\bo_bi\.nuget\packages\libsodium-uwp\0.1.0-alpha5\runtimes\win10-arm\native\Sodium.winmd
1>C:\Program Files (x86)\MSBuild\Microsoft\VisualStudio\v14.0\AppxPackage\Microsoft.AppXPackage.Targets(1692,5): error APPX1101: C:\Users\bo_bi\.nuget\packages\libsodium-uwp\0.1.0-alpha5\lib\uap10.0\Sodium.winmd`

Building with target x86 is no problem.

**Comment by charlesportwoodii** [comment]
@BoBiene I'm pretty sure that's a packaging problem with the `Nuget` package. I haven't worked out all the details yet with packaging UWP for Nuget. Try cloning the project and including it as a source for now. It's alpha still.

**Comment by BoBiene** [comment]
No problem. 
I have added it as a submodule an included it in my Solution. 
Now it is compiling in ARM :)

Thanks alot.

**Comment by charlesportwoodii** [comment]
The next release Alpha should have this fixed. I'm closing this for now though.
